### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by 8cH9azbsFifZ** [SeriousBuggie/UZ#1]
Could you provide build instructions on how to compile? I was not able to compile the source using the headers (../Core/Inc from the public UT sources). The binary is not running under debian / ubuntu.

**Comment by SeriousBuggie** [comment]
See `comp.sh` in the release ZIP for build script. I use it in Ubuntu 12.04 - all fine.
Binary possible not run because you not meet some dependencies.
Use some special tools for find which one and install it.

Also you possible need gcc-2.95 or you not able link with UT code.

Headers near same as original. Except few fixes of AntraX and me.

**Comment by 8cH9azbsFifZ** [comment]
Good hint :) I am now able to compile the first files with a docker container using an old debian image. Seems like I am missing  your patches for the headers now. Can you give a further hint on this, so I can provide a self-contained docker-container with platform indenpendent binaries.

**Comment by SeriousBuggie** [comment]
Try start from here: https://ut99.org/viewtopic.php?p=39260#p39260

**Comment by 8cH9azbsFifZ** [comment]
I have downloaded the original headers and the patches provided in the .rar file mentioned in the post above. Still compiling yields a lot of failures, i.e.:

```
In file included from ../headers/Core/Inc/Core.h:61,
                 from ./UZ.cpp:14:
../headers/Core/Inc/UnGnuG.h:129: no data type for mode `TI'
../headers/Core/Inc/UnGnuG.h: In function `INT appRound(float)':
../headers/Core/Inc/UnGnuG.h:216: `F' undeclared (first use this function)
../headers/Core/Inc/UnGnuG.h:216: (Each undeclared identifier is reported only once
../headers/Core/Inc/UnGnuG.h:216: for each function it appears in.)
In file included from ../headers/Core/Inc/Core.h:389,
                 from ./UZ.cpp:14:
```
.....

so far I my docker file is able to compile the binaries partially (using debian sarge and gcc-2.95). Any further suggestions on the patches?

**Comment by SeriousBuggie** [comment]
Then you need investigate and fix headers.
You can also try this: [Deps.zip](https://github.com/SeriousBuggie/UZ/files/6489985/Deps.zip)
